# ----------------------- #
#      Main Configs       #
# ----------------------- #

baseurl: "edercervantes.github.io"
url: http://yoursite.com
title: Home
email: eder.cervantesalcala@gmail.com
author: Eder Cervantes
description: > # "Personal website for Eder Cervantes 
  Personal website for Eder Cervantes 
copyright: 'Copyright &copy; 2015 Eder Cervantes. All Rights Reserved.'
credits: 'Hope you have a nice day 😀'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/EderCervantes17
  - title: github
    url: https://github.com/edercervantes
  - title: linkedin
    url: https://www.linkedin.com/in/eder-cervantes-alcala/
