# ----------------------- #
#      Main Configs       #
# ----------------------- #

baseurl: "edercervantes.github.io"
url: http://yoursite.com
title: Home
email: eder.cervantesalcala@gmail.com
author: Eder Cervantes
description: > # "Personal website for Eder Cervantes 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2015 Eder Cervantes. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/EderCervantes17
  - title: github
    url: https://github.com/edercervantes
  - title: linkedin
    url: https://www.linkedin.com/in/eder-cervantes-alcala/
